#!/usr/bin/env python3
"""
asset_ledger/scan.py - M.E.R.L.I.N. asset reference scanner.

Parses the whole Godot project tree and builds a reference graph of res:// game
assets: which files are reachable from the game roots (project.godot main_scene,
autoloads, enabled plugins, export presets) and which are orphans.

It ALSO reports "disk pressure": large regenerable / historical directories
(node_modules, .godot, build caches, tmp, ...) that are excluded from the game
graph but are the real disk hogs. This directly serves "libérer le disque".

Outputs (under docs/asset-ledger/):
  - graph.json  : machine-readable graph + disk pressure (consumed by cleanup.py / watchdog.py)
  - BIBLE.md    : human-readable "bible", kept up to date on every scan (with changelog delta)

Pure stdlib (Python 3.12). Content hash = blake2b (blake3 not installed).
No writes outside docs/asset-ledger/. Never deletes anything.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from collections import defaultdict, deque
from datetime import datetime, timezone
from pathlib import Path

SCHEMA_VERSION = 3  # bump when graph.json shape changes

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #

# Directories that are regenerable / historical / non-res:// game content.
# They are PRUNED from the reference graph and reported under disk_pressure.
REGEN_DIR_NAMES = {
    ".git", ".godot", "node_modules", "__pycache__", ".venv", "venv",
    "build", "dist", "out", "output", "tmp", "tmp_xlsx", "catboost_info",
    "scene_screenshots", "_anim_test", ".sharp", ".pytest_cache", ".mypy_cache",
    ".claude",  # worktrees + local caches (never part of the shipped game)
}
# Regenerable note per dir name (why it is safe to purge).
REGEN_NOTE = {
    ".godot": "Godot import/edit cache - regenerated on next editor open",
    "node_modules": "npm deps - restore via `npm install`",
    "__pycache__": "Python bytecode cache - regenerated on import",
    ".venv": "Python virtualenv - recreate from requirements",
    "venv": "Python virtualenv - recreate from requirements",
    "build": "Build artifacts - regenerated by build step",
    "dist": "Build/dist artifacts - regenerated by build step",
    "output": "Generated output - regenerated by tooling",
    "tmp": "Temporary files",
    "tmp_xlsx": "Temporary xlsx working dir",
    "catboost_info": "CatBoost training logs - regenerable",
    "scene_screenshots": "QA screenshots - regenerable via smoke capture",
    "_anim_test": "Animation test scratch",
    ".sharp": "sharp binary cache - reinstalled by npm",
    ".git": "Git object store (do NOT purge blindly; listed for size awareness)",
    ".claude": "Claude Code worktrees & local caches",
}

# Extensions that count as tracked "game assets" (nodes in the graph).
GAME_EXTS = {
    # code
    ".gd", ".gdshader", ".shader",
    # scenes / resources
    ".tscn", ".scn", ".tres", ".res",
    # textures / images
    ".png", ".jpg", ".jpeg", ".webp", ".svg", ".bmp", ".ktx", ".ctex", ".exr", ".hdr",
    # audio
    ".ogg", ".wav", ".mp3",
    # 3D
    ".glb", ".gltf", ".obj", ".mtl", ".fbx", ".escn", ".dae",
    # fonts
    ".ttf", ".otf", ".fnt", ".fontdata",
    # data / i18n / config
    ".json", ".translation", ".po", ".csv", ".cfg",
    # narrative / lore (kept, but only orphan-flagged, never auto-deleted)
    ".md", ".txt",
}

# Categorisation by extension.
TYPE_BY_EXT = {
    ".gd": "script", ".gdshader": "shader", ".shader": "shader",
    ".tscn": "scene", ".scn": "scene", ".tres": "resource", ".res": "resource",
    ".png": "texture", ".jpg": "texture", ".jpeg": "texture", ".webp": "texture",
    ".svg": "texture", ".bmp": "texture", ".ktx": "texture", ".ctex": "texture",
    ".exr": "texture", ".hdr": "texture",
    ".ogg": "audio", ".wav": "audio", ".mp3": "audio",
    ".glb": "model", ".gltf": "model", ".obj": "model", ".mtl": "model",
    ".fbx": "model", ".escn": "model", ".dae": "model",
    ".ttf": "font", ".otf": "font", ".fnt": "font", ".fontdata": "font",
    ".json": "config", ".cfg": "config",
    ".translation": "i18n", ".po": "i18n", ".csv": "data",
    ".md": "lore", ".txt": "lore",
}

# Files that must NEVER be flagged deletable (whitelist by name / suffix / path prefix).
WHITELIST_NAMES = {
    "project.godot", "export_presets.cfg", ".gitignore", ".gitattributes",
    "LICENSE", "LICENSE.md", "LICENSE.txt", "icon.svg", "default_bus_layout.tres",
    ".asset-keep", "CLAUDE.md", "AGENTS.md", "PROJECT.md", "ROADMAP.md",
    # tooling manifests / configs that live at root but are not game assets
    "package.json", "package-lock.json", "pnpm-lock.yaml", ".mcp.json",
    "tsconfig.json", ".npmrc", "Modelfile", "validate.bat",
}
WHITELIST_PREFIXES = ("docs/", "tests/")  # always protected trees (relative, posix)

# Top-level subtrees that are NOT part of the shipped Godot res:// game runtime:
# tooling, web demos, servers, native build workspaces, historical archives.
# Their source files are EXCLUDED from the game reference graph (never deletion
# candidates), but regenerable caches inside them (node_modules, build) are still
# captured as disk pressure and remain purgeable.
OUT_OF_SCOPE_TOP = {
    "tools", "server", "server-trellis", "web-demo", "external", "native",
    "ollama-proxy", "llm_simple", "archive",
}
# Any directory containing one of these marker files is a foreign subproject
# (node/native/python) whose sources are out of scope for the game graph.
SUBPROJECT_MARKERS = {"package.json", "CMakeLists.txt", "Cargo.toml"}

# Text files we parse for references.
PARSE_EXTS = {".gd", ".tscn", ".scn", ".tres", ".res", ".cfg", ".godot",
              ".import", ".json", ".md", ".txt", ".gdshader", ".shader", ".po"}

MAX_PARSE_BYTES = 4 * 1024 * 1024   # skip ref-parsing of files bigger than this
MAX_HASH_BYTES = 64 * 1024 * 1024   # skip content hash of files bigger than this

RES_RE = re.compile(r'res://[^"\'\)\s\]<>]+')
CLASS_NAME_RE = re.compile(r'^\s*class_name\s+([A-Za-z_][A-Za-z0-9_]*)', re.M)
# Dynamic path heuristics: a res:// literal containing a format/concat marker,
# OR a string prefix that is later concatenated. We capture the static prefix.
DYN_RE = re.compile(r'res://[^"\'\)]*?(?:%s|%d|%[0-9.]*[sdfx]|\{|\}|"\s*\+|\+\s*")')
IDENT_RE = re.compile(r'[A-Za-z_][A-Za-z0-9_]*')


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #

def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def human(n: int) -> str:
    f = float(n)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if f < 1024 or unit == "TB":
            return f"{f:.1f} {unit}" if unit != "B" else f"{int(f)} B"
        f /= 1024
    return f"{f:.1f} TB"


def content_hash(path: Path, size: int) -> str:
    if size > MAX_HASH_BYTES:
        return f"skip:{size}"
    h = hashlib.blake2b(digest_size=16)
    try:
        with open(path, "rb") as fh:
            for chunk in iter(lambda: fh.read(1024 * 256), b""):
                h.update(chunk)
    except OSError:
        return "unreadable"
    return h.hexdigest()


def read_text(path: Path, size: int) -> str:
    if size > MAX_PARSE_BYTES:
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def git_tracked_set(root: Path) -> set[str]:
    try:
        out = subprocess.run(
            ["git", "ls-files"], cwd=root, capture_output=True, text=True, timeout=120
        )
        if out.returncode == 0:
            return {line.strip().replace("\\", "/") for line in out.stdout.splitlines() if line.strip()}
    except (OSError, subprocess.SubprocessError):
        pass
    return set()


def dir_size(path: Path, budget_s: float = 8.0) -> tuple[int, bool]:
    """Sum file sizes under path. Returns (bytes, complete?). Time-bounded."""
    import time
    total = 0
    start = time.time()
    complete = True
    for dp, dn, fn in os.walk(path):
        if time.time() - start > budget_s:
            complete = False
            break
        for f in fn:
            try:
                total += os.path.getsize(os.path.join(dp, f))
            except OSError:
                pass
    return total, complete


# --------------------------------------------------------------------------- #
# Scan
# --------------------------------------------------------------------------- #

def load_enabled_plugins(root: Path) -> set[str]:
    """Return posix dir prefixes of enabled editor plugins, e.g. 'addons/godot_mcp/'."""
    prefixes: set[str] = set()
    proj = root / "project.godot"
    if proj.exists():
        txt = proj.read_text(encoding="utf-8", errors="ignore")
        m = re.search(r'enabled=PackedStringArray\(([^)]*)\)', txt)
        if m:
            for p in RES_RE.findall(m.group(1)):
                # res://addons/<name>/plugin.cfg -> addons/<name>/
                rel = p[len("res://"):]
                parts = rel.split("/")
                if len(parts) >= 2 and parts[0] == "addons":
                    prefixes.add(f"addons/{parts[1]}/")
    return prefixes


def collect_roots(root: Path) -> tuple[set[str], list[str]]:
    """Return (root_res_paths, root_source_labels). Roots seed reachability."""
    roots: set[str] = set()
    labels: list[str] = []
    proj = root / "project.godot"
    if proj.exists():
        txt = proj.read_text(encoding="utf-8", errors="ignore")
        for p in RES_RE.findall(txt):
            roots.add(p)
        labels.append("project.godot")
    presets = root / "export_presets.cfg"
    if presets.exists():
        txt = presets.read_text(encoding="utf-8", errors="ignore")
        for p in RES_RE.findall(txt):
            roots.add(p)
        labels.append("export_presets.cfg")
    return roots, labels


def scan(root: Path) -> dict:
    tracked = git_tracked_set(root)
    enabled_plugins = load_enabled_plugins(root)
    root_res, root_labels = collect_roots(root)

    nodes: dict[str, dict] = {}          # res_path -> node
    class_to_res: dict[str, str] = {}    # class_name -> res_path
    static_edges: dict[str, set[str]] = defaultdict(set)   # from -> {to}
    dynamic_prefixes: set[str] = set()   # static prefixes of dynamic paths
    dynamic_sources: dict[str, set[str]] = defaultdict(set)  # prefix -> {from}
    file_texts: dict[str, str] = {}      # res_path -> text (parse cache for class refs)

    disk_pressure: list[dict] = []
    seen_regen_dirs: set[str] = set()
    oos_prefixes: set[str] = set()       # out-of-scope subtree prefixes (posix, trailing /)
    out_of_scope: list[dict] = []        # reported foreign subtrees (tooling/web/native)

    # ---- walk ----
    for dp, dn, fn in os.walk(root):
        rel_dir = Path(dp).relative_to(root).as_posix()

        # detect foreign subprojects (marker files) -> mark subtree out of scope,
        # but keep descending so regen caches inside (node_modules, build) are captured.
        if rel_dir != "." and rel_dir + "/" not in oos_prefixes:
            is_top_tool = "/" not in rel_dir and rel_dir in OUT_OF_SCOPE_TOP
            has_marker = any(m in fn for m in SUBPROJECT_MARKERS)
            if is_top_tool or has_marker:
                if not any(rel_dir.startswith(p) for p in oos_prefixes):
                    oos_prefixes.add(rel_dir + "/")
                    out_of_scope.append({
                        "path": rel_dir,
                        "reason": "top-level tooling/subproject" if is_top_tool else "foreign subproject (marker file)",
                    })
        in_scope = not any((rel_dir + "/").startswith(p) or rel_dir + "/" in oos_prefixes
                           for p in oos_prefixes)

        # prune + record regen dirs and ALL hidden (dot) dirs (never game assets)
        pruned = []
        for d in list(dn):
            is_regen = d in REGEN_DIR_NAMES
            is_dot = d.startswith(".")
            if is_regen or is_dot:
                full = Path(dp) / d
                rel = full.relative_to(root).as_posix()
                if rel not in seen_regen_dirs:
                    seen_regen_dirs.add(rel)
                    sz, complete = dir_size(full)
                    disk_pressure.append({
                        "path": rel,
                        "size_bytes": sz,
                        "size_complete": complete,
                        "regenerable": d not in (".git",),
                        "note": REGEN_NOTE.get(d, "hidden/tooling dir (not game content)"),
                    })
                pruned.append(d)
        for d in pruned:
            dn.remove(d)

        if not in_scope:
            continue  # foreign subtree: sources excluded from game graph (caches already captured above)

        for f in fn:
            ext = os.path.splitext(f)[1].lower()
            full = Path(dp) / f
            rel = full.relative_to(root).as_posix()
            res_path = "res://" + rel
            try:
                st = full.stat()
            except OSError:
                continue
            size = st.st_size

            if ext not in GAME_EXTS:
                continue  # non-game files ignored in the graph (still on disk)

            node = {
                "path": res_path,
                "rel": rel,
                "type": TYPE_BY_EXT.get(ext, "other"),
                "ext": ext,
                "size_bytes": size,
                "mtime": datetime.fromtimestamp(st.st_mtime, timezone.utc).strftime("%Y-%m-%d"),
                "hash": content_hash(full, size),
                "git_tracked": rel in tracked,
                "referenced_by": [],
                "reference_confidence": "none",
                "reachable": False,
                "status": "unknown",
            }
            nodes[res_path] = node

            if ext in PARSE_EXTS:
                txt = read_text(full, size)
                if txt:
                    file_texts[res_path] = txt
                    for cm in CLASS_NAME_RE.finditer(txt):
                        class_to_res[cm.group(1)] = res_path
                    for ref in RES_RE.findall(txt):
                        ref = ref.rstrip('.,;')
                        if ref != res_path:
                            static_edges[res_path].add(ref)
                    for dm in DYN_RE.finditer(txt):
                        frag = dm.group(0)
                        prefix = re.split(r'%|\{|"\s*\+|\+\s*"', frag)[0]
                        prefix = prefix.rsplit("/", 1)[0] + "/" if "/" in prefix[len("res://"):] else prefix
                        if len(prefix) > len("res://"):
                            dynamic_prefixes.add(prefix)
                            dynamic_sources[prefix].add(res_path)

    # ---- class_name usage edges (script referenced as a type/identifier) ----
    corpus_idents: set[str] = set()   # every identifier token across the codebase
    for src, txt in file_texts.items():
        idents = set(IDENT_RE.findall(txt))
        corpus_idents |= idents
        if not src.endswith(".gd"):
            continue
        for cname, target in class_to_res.items():
            if target == src:
                continue
            if cname in idents:
                static_edges[src].add(target)

    # ---- dynamic tagging: any node whose path starts with a dynamic prefix ----
    for res_path, node in nodes.items():
        for pref in dynamic_prefixes:
            if res_path.startswith(pref):
                node["reference_confidence"] = "dynamic"
                node["referenced_by"] = sorted(dynamic_sources.get(pref, []))
                break

    # ---- reachability BFS from roots ----
    # Seed: explicit roots + enabled-plugin trees + autoload/main scene already in root_res.
    reachable: set[str] = set()
    q: deque[str] = deque()
    for r in root_res:
        if r in nodes:
            reachable.add(r)
            q.append(r)
    # plugin trees are reachable as a unit
    for res_path, node in nodes.items():
        rel = node["rel"]
        for pref in enabled_plugins:
            if rel.startswith(pref):
                if res_path not in reachable:
                    reachable.add(res_path)
                    q.append(res_path)
                node["referenced_by"].append("enabled-plugin")
                break

    while q:
        cur = q.popleft()
        for nxt in static_edges.get(cur, ()):
            if nxt in nodes:
                nodes[nxt]["referenced_by"].append(cur)
                if nodes[nxt]["reference_confidence"] == "none":
                    nodes[nxt]["reference_confidence"] = "static"
                if nxt not in reachable:
                    reachable.add(nxt)
                    q.append(nxt)

    # ---- finalize node status ----
    # Code-like assets can be loaded by logical name (scene transitions, autoload
    # UI, ShaderMaterial by name). If such a file's stem (or its PascalCase form)
    # appears as an identifier anywhere, treat it as a soft/dynamic reference and
    # DO NOT flag it deletable: it goes to the manual-verify list instead.
    SOFT_REF_TYPES = {"scene", "script", "shader", "resource"}

    def soft_referenced(rel: str) -> bool:
        stem = os.path.splitext(os.path.basename(rel))[0]
        if len(stem) < 4:
            return False
        camel = "".join(p.capitalize() for p in stem.split("_"))
        return stem in corpus_idents or camel in corpus_idents

    counts = defaultdict(int)
    for res_path, node in nodes.items():
        rel = node["rel"]
        name = os.path.basename(rel)
        node["reachable"] = res_path in reachable
        node["referenced_by"] = sorted(set(node["referenced_by"]))[:20]

        whitelisted = (
            name in WHITELIST_NAMES
            or any(rel.startswith(p) for p in WHITELIST_PREFIXES)
            or rel.startswith("addons/")            # addon internals: never auto-delete
            or "/i18n/" in rel or rel.endswith(".translation")
        )
        if res_path in root_res:
            node["status"] = "root"
        elif whitelisted:
            node["status"] = "whitelisted"
        elif node["reachable"]:
            node["status"] = "used"
        elif node["reference_confidence"] == "dynamic":
            node["status"] = "dynamic_uncertain"
        elif node["type"] in SOFT_REF_TYPES and soft_referenced(rel):
            node["status"] = "dynamic_uncertain"     # name mentioned somewhere: verify manually
            node["reference_confidence"] = "dynamic"
        elif node["type"] == "lore":
            node["status"] = "orphan_lore"      # narrative: flag, never auto-delete
        else:
            node["status"] = "orphan_static"    # safe deletion candidate
        counts[node["status"]] += 1

    total_bytes = sum(n["size_bytes"] for n in nodes.values())
    orphan_static_bytes = sum(n["size_bytes"] for n in nodes.values() if n["status"] == "orphan_static")
    disk_pressure.sort(key=lambda d: d["size_bytes"], reverse=True)

    graph = {
        "schema_version": SCHEMA_VERSION,
        "generated": now_iso(),
        "root": str(root),
        "summary": {
            "total_files": len(nodes),
            "total_bytes": total_bytes,
            "status_counts": dict(counts),
            "orphan_static_bytes": orphan_static_bytes,
            "disk_pressure_bytes": sum(d["size_bytes"] for d in disk_pressure),
        },
        "dynamic_patterns": sorted(dynamic_prefixes),
        "out_of_scope": sorted(out_of_scope, key=lambda d: d["path"]),
        "disk_pressure": disk_pressure,
        "nodes": sorted(nodes.values(), key=lambda n: (-n["size_bytes"], n["path"])),
    }
    return graph


# --------------------------------------------------------------------------- #
# BIBLE.md rendering (+ changelog delta vs previous graph)
# --------------------------------------------------------------------------- #

def render_bible(graph: dict, prev: dict | None) -> str:
    s = graph["summary"]
    L: list[str] = []
    L.append(f"# Asset Ledger - Bible M.E.R.L.I.N.")
    L.append("")
    L.append(f"> Généré le {graph['generated']} par `tools/asset_ledger/scan.py` "
             f"(schema v{graph['schema_version']}). Source de vérité de l'inventaire d'assets. "
             "Ne PAS éditer à la main : régénéré à chaque scan.")
    L.append("")
    L.append("## Résumé")
    L.append("")
    L.append(f"- **Fichiers game-asset suivis** : {s['total_files']} ({human(s['total_bytes'])})")
    cc = s["status_counts"]
    L.append(f"- **Utilisés** : {cc.get('used',0) + cc.get('root',0) + cc.get('whitelisted',0)} "
             f"(dont racines {cc.get('root',0)}, whitelist {cc.get('whitelisted',0)})")
    L.append(f"- **Orphelins statiques (supprimables)** : {cc.get('orphan_static',0)} "
             f"→ {human(s['orphan_static_bytes'])} récupérables")
    L.append(f"- **Orphelins lore (à revoir, jamais auto-suppr.)** : {cc.get('orphan_lore',0)}")
    L.append(f"- **Références dynamiques (incertain)** : {cc.get('dynamic_uncertain',0)}")
    L.append("")
    L.append(f"- **Pression disque (regénérable/historique, hors graphe)** : "
             f"{human(s['disk_pressure_bytes'])} sur {len(graph['disk_pressure'])} dossiers")
    L.append("")

    # Disk pressure table (the real disk hogs)
    L.append("## Pression disque - dossiers regénérables / historiques")
    L.append("")
    L.append("Exclus du graphe de références (non-`res://` game content). Cible n°1 pour libérer le disque.")
    L.append("")
    L.append("| dossier | taille | regénérable | note |")
    L.append("|---|---:|:---:|---|")
    for d in graph["disk_pressure"][:25]:
        star = "" if d.get("size_complete", True) else " (≥)"
        L.append(f"| `{d['path']}` | {human(d['size_bytes'])}{star} | "
                 f"{'oui' if d['regenerable'] else 'NON'} | {d['note']} |")
    L.append("")

    # Top orphans
    orphans = [n for n in graph["nodes"] if n["status"] == "orphan_static"]
    orphans_sorted = sorted(orphans, key=lambda n: -n["size_bytes"])
    L.append("## Top orphelins statiques (candidats suppression sûre)")
    L.append("")
    if orphans_sorted:
        L.append("| chemin | taille | type | dernière modif | git |")
        L.append("|---|---:|---|---|:---:|")
        for n in orphans_sorted[:30]:
            L.append(f"| `{n['path']}` | {human(n['size_bytes'])} | {n['type']} | "
                     f"{n['mtime']} | {'yes' if n['git_tracked'] else '-'} |")
    else:
        L.append("*Aucun orphelin statique détecté.* 🎉")
    L.append("")

    # By category
    L.append("## Par catégorie")
    L.append("")
    by_type: dict[str, list] = defaultdict(list)
    for n in graph["nodes"]:
        by_type[n["type"]].append(n)
    for typ in sorted(by_type):
        items = by_type[typ]
        tb = sum(n["size_bytes"] for n in items)
        used = sum(1 for n in items if n["status"] in ("used", "root", "whitelisted"))
        orph = sum(1 for n in items if n["status"] == "orphan_static")
        L.append(f"### {typ} - {len(items)} fichiers, {human(tb)} "
                 f"(utilisés {used}, orphelins {orph})")
    L.append("")

    # Dynamic patterns to verify
    L.append("## Références dynamiques à vérifier manuellement")
    L.append("")
    if graph["dynamic_patterns"]:
        for p in graph["dynamic_patterns"]:
            L.append(f"- `{p}` (chemin calculé - les fichiers sous ce préfixe sont marqués incertains)")
    else:
        L.append("*Aucun préfixe dynamique détecté.*")
    L.append("")

    # Changelog delta
    L.append("## Changelog auto (delta depuis dernier scan)")
    L.append("")
    if prev:
        prev_paths = {n["path"]: n for n in prev.get("nodes", [])}
        cur_paths = {n["path"]: n for n in graph["nodes"]}
        added = [p for p in cur_paths if p not in prev_paths]
        removed = [p for p in prev_paths if p not in cur_paths]
        newly_orphan = [p for p, n in cur_paths.items()
                        if n["status"] == "orphan_static"
                        and prev_paths.get(p, {}).get("status") not in (None, "orphan_static")]
        L.append(f"- Depuis {prev.get('generated','?')}")
        L.append(f"- Ajoutés : {len(added)} · Retirés : {len(removed)} · Nouveaux orphelins : {len(newly_orphan)}")
        for p in added[:15]:
            L.append(f"  - `+` {p}")
        for p in removed[:15]:
            L.append(f"  - `-` {p}")
        for p in newly_orphan[:15]:
            L.append(f"  - `⚠ orphelin` {p}")
    else:
        L.append("*Premier scan - pas de delta.*")
    L.append("")
    L.append("---")
    L.append("*Régénérer : `python tools/asset_ledger/scan.py`. "
             "Nettoyage : `python tools/asset_ledger/cleanup.py`. "
             "Surveillance : `python tools/asset_ledger/watchdog.py`.*")
    return "\n".join(L) + "\n"


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def main() -> int:
    ap = argparse.ArgumentParser(description="M.E.R.L.I.N. asset reference scanner")
    ap.add_argument("--root", default=".", help="Godot project root (default: cwd)")
    ap.add_argument("--out", default="docs/asset-ledger", help="output dir")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    out_dir = (root / args.out) if not os.path.isabs(args.out) else Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    graph_path = out_dir / "graph.json"
    bible_path = out_dir / "BIBLE.md"

    prev = None
    if graph_path.exists():
        try:
            prev = json.loads(graph_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            prev = None

    if not args.quiet:
        print(f"[scan] scanning {root} ...", file=sys.stderr)
    graph = scan(root)

    graph_path.write_text(json.dumps(graph, ensure_ascii=False, indent=1), encoding="utf-8")
    bible_path.write_text(render_bible(graph, prev), encoding="utf-8")

    s = graph["summary"]
    if not args.quiet:
        print(f"[scan] {s['total_files']} game files, {human(s['total_bytes'])}", file=sys.stderr)
        print(f"[scan] orphan_static: {s['status_counts'].get('orphan_static',0)} "
              f"({human(s['orphan_static_bytes'])} recoverable)", file=sys.stderr)
        print(f"[scan] disk pressure: {human(s['disk_pressure_bytes'])} "
              f"across {len(graph['disk_pressure'])} regen dirs", file=sys.stderr)
        print(f"[scan] wrote {graph_path} + {bible_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
