## BestioleSprite — AnimatedSprite2D wrapper for pixel art bestiole.
## Drop-in replacement for BestioleCreature (procedural blob).
## Loads the multi-animation SpriteFrames resource generated by the pixel art pipeline.
## Same interface: setup(), assemble(), state_changed signal, creature_clicked signal.

class_name BestioleSprite
extends Control

signal assembly_complete
signal creature_clicked
signal state_changed(new_state: String)
signal animation_changed(old_anim: String, new_anim: String)

# ═══════════════════════════════════════════════════════════════════════════════
# RESOURCE PATH
# ═══════════════════════════════════════════════════════════════════════════════

const FRAMES_PATH := "res://sprites/pixel_art/bestiole/bestiole_frames.tres"

# ═══════════════════════════════════════════════════════════════════════════════
# STATE MACHINE — mirrors BestioleCreature states
# ═══════════════════════════════════════════════════════════════════════════════

enum CreatureState { IDLE, WANDER, CURIOUS, JUMP, LAND, SLEEPY, STARTLED }

## Map CreatureState -> sprite animation name
const STATE_ANIM_MAP: Dictionary = {
	CreatureState.IDLE: "idle",
	CreatureState.WANDER: "walk",
	CreatureState.CURIOUS: "curious",
	CreatureState.JUMP: "excited",
	CreatureState.LAND: "alert",
	CreatureState.SLEEPY: "sleep",
	CreatureState.STARTLED: "scared",
}

## State timings (same as BestioleCreature)
const T_IDLE_MIN := 1.0
const T_IDLE_MAX := 3.2
const T_CURIOUS := 2.5
const T_SLEEPY := 6.5
const T_LAND := 0.18
const T_STARTLE := 0.32
const JUMP_CHANCE := 0.15
const SLEEPY_CHANCE := 0.06
const ARRIVE_DIST := 15.0

# ═══════════════════════════════════════════════════════════════════════════════
# MOVEMENT
# ═══════════════════════════════════════════════════════════════════════════════

const MOVE_SPEED := 80.0
const FRICTION := 0.87

# ═══════════════════════════════════════════════════════════════════════════════
# SQUASH & STRETCH (spring physics — matches BestioleCreature)
# ═══════════════════════════════════════════════════════════════════════════════

const SS_K := 24.0        # Spring stiffness
const SS_DAMP := 0.75     # Damping coefficient
const SS_REST := 1.0      # Rest scale

# ═══════════════════════════════════════════════════════════════════════════════
# PARTICLES (CPU pixel dust)
# ═══════════════════════════════════════════════════════════════════════════════

const MAX_PARTICLES := 40
const PARTICLE_GRAVITY := 240.0
const PARTICLE_X_DAMP := 0.97

# ═══════════════════════════════════════════════════════════════════════════════
# TRAIL (afterimage history)
# ═══════════════════════════════════════════════════════════════════════════════

const TRAIL_LENGTH := 6
const TRAIL_INTERVAL := 0.03     # seconds between captures
const TRAIL_VEL_THRESHOLD := 30.0  # minimum speed to show trail

# ═══════════════════════════════════════════════════════════════════════════════
# VARIABLES
# ═══════════════════════════════════════════════════════════════════════════════

var _sprite: AnimatedSprite2D
var _frames_res: SpriteFrames
var _assembled: bool = false
var _target_size: float = 120.0
var _sprite_scale: float = 1.0

# State machine
var _state: CreatureState = CreatureState.IDLE
var _timer: float = 0.0
var _wander_target: Vector2 = Vector2.ZERO
var _facing: float = 1.0

# Position within parent bounds
var _local_pos: Vector2 = Vector2.ZERO
var _vel: Vector2 = Vector2.ZERO

# Animation queue + crossfade
var _queued_anim: String = ""
var _current_anim: String = "idle"
var _crossfading: bool = false
var _crossfade_sprite: AnimatedSprite2D  # second sprite for crossfade
const CROSSFADE_DURATION := 0.15  # seconds for blend transition

# Animation priority (higher = more important, cannot be interrupted by lower)
const ANIM_PRIORITY: Dictionary = {
	"idle": 0, "walk": 1, "blink": 1,
	"curious": 2, "happy": 2, "sad": 2,
	"excited": 3, "alert": 3, "scared": 3,
	"sleep": 4,
}

# Blink overlay
var _blink_timer: float = 3.0

# Bond level (gameplay)
var _bond_level: int = 0
var _awen: int = 0

# Squash & stretch state
var _ss: Vector2 = Vector2(SS_REST, SS_REST)
var _ss_vel: Vector2 = Vector2.ZERO

# Particles state
var _particles: Array[Dictionary] = []

# Trail state
var _trail: Array[Dictionary] = []
var _trail_timer: float = 0.0

# Shader squish
var _squish_material: ShaderMaterial


# ═══════════════════════════════════════════════════════════════════════════════
# SETUP
# ═══════════════════════════════════════════════════════════════════════════════

func setup(target_size: float = 120.0) -> void:
	_target_size = target_size
	custom_minimum_size = Vector2(target_size, target_size)
	size = Vector2(target_size, target_size)
	mouse_filter = Control.MOUSE_FILTER_PASS


func assemble(instant: bool = false) -> void:
	_assembled = false
	_state = CreatureState.IDLE
	_timer = randf_range(T_IDLE_MIN, T_IDLE_MAX)
	_blink_timer = randf_range(2.0, 4.5)
	_vel = Vector2.ZERO
	_facing = 1.0

	# Load SpriteFrames resource
	_frames_res = load(FRAMES_PATH) as SpriteFrames
	if _frames_res == null:
		push_warning("BestioleSprite: could not load " + FRAMES_PATH)
		_assembled = true
		assembly_complete.emit()
		return

	# Create AnimatedSprite2D child (main)
	if _sprite == null:
		_sprite = AnimatedSprite2D.new()
		_sprite.centered = true
		add_child(_sprite)
		_sprite.animation_finished.connect(_on_animation_finished)

	# Create crossfade sprite (for blend transitions)
	if _crossfade_sprite == null:
		_crossfade_sprite = AnimatedSprite2D.new()
		_crossfade_sprite.centered = true
		_crossfade_sprite.modulate.a = 0.0
		_crossfade_sprite.visible = false
		add_child(_crossfade_sprite)

	_sprite.sprite_frames = _frames_res
	_crossfade_sprite.sprite_frames = _frames_res

	# Load squish shader material
	var shader: Shader = load("res://shaders/bestiole_squish.gdshader") as Shader
	if shader != null:
		_squish_material = ShaderMaterial.new()
		_squish_material.shader = shader
		_sprite.material = _squish_material

	# Scale sprite to fit target_size (frames are 128x128)
	_sprite_scale = _target_size / 128.0
	_sprite.scale = Vector2(_sprite_scale, _sprite_scale)
	_sprite.position = Vector2(_target_size * 0.5, _target_size * 0.5)
	_crossfade_sprite.scale = Vector2(_sprite_scale, _sprite_scale)
	_crossfade_sprite.position = _sprite.position

	# Start position centered in parent
	var bounds: Vector2 = _get_bounds()
	_local_pos = Vector2(bounds.x * 0.5, bounds.y * 0.65)

	_play_animation("idle")

	if instant:
		_assembled = true
		assembly_complete.emit()
	else:
		# Pop-in effect: scale from 0 to 1
		_sprite.scale = Vector2.ZERO
		var tween := create_tween()
		tween.tween_property(_sprite, "scale",
			Vector2(_sprite_scale, _sprite_scale), 0.4).set_ease(Tween.EASE_OUT).set_trans(Tween.TRANS_ELASTIC)
		tween.tween_callback(func():
			_assembled = true
			assembly_complete.emit()
		)


# ═══════════════════════════════════════════════════════════════════════════════
# ANIMATION CONTROL
# ═══════════════════════════════════════════════════════════════════════════════

func play_animation(anim_name: String) -> void:
	"""Public API: immediately play an animation."""
	_play_animation(anim_name)


func queue_animation(anim_name: String) -> void:
	"""Public API: queue animation to play after current cycle finishes."""
	if _current_anim == anim_name:
		return
	_queued_anim = anim_name


func get_current_animation() -> String:
	return _current_anim


func _play_animation(anim_name: String, crossfade: bool = true) -> void:
	if _sprite == null or _frames_res == null:
		return
	if not _frames_res.has_animation(anim_name):
		push_warning("BestioleSprite: unknown animation '%s'" % anim_name)
		return
	if anim_name == _current_anim:
		return

	var old: String = _current_anim

	if crossfade and _crossfade_sprite != null and old != "":
		# Start crossfade: old anim fades out, new anim fades in
		_crossfade_sprite.visible = true
		_crossfade_sprite.sprite_frames = _frames_res
		_crossfade_sprite.play(old)
		_crossfade_sprite.frame = _sprite.frame
		_crossfade_sprite.modulate.a = 1.0
		_crossfade_sprite.flip_h = _sprite.flip_h

		_sprite.play(anim_name)
		_sprite.modulate.a = 0.0

		# Tween crossfade
		var tween := create_tween()
		tween.set_parallel(true)
		tween.tween_property(_sprite, "modulate:a", 1.0, CROSSFADE_DURATION)
		tween.tween_property(_crossfade_sprite, "modulate:a", 0.0, CROSSFADE_DURATION)
		tween.chain().tween_callback(func():
			_crossfade_sprite.visible = false
			_crossfading = false
		)
		_crossfading = true
	else:
		_sprite.play(anim_name)

	_current_anim = anim_name
	_queued_anim = ""

	if old != anim_name:
		animation_changed.emit(old, anim_name)


func _on_animation_finished() -> void:
	# Play queued animation if any
	if _queued_anim != "" and _queued_anim != _current_anim:
		_play_animation(_queued_anim)


# ═══════════════════════════════════════════════════════════════════════════════
# STATE MACHINE
# ═══════════════════════════════════════════════════════════════════════════════

func _enter_state(new_state: CreatureState) -> void:
	_state = new_state
	var anim: String = STATE_ANIM_MAP.get(new_state, "idle")

	match new_state:
		CreatureState.IDLE:
			_timer = randf_range(T_IDLE_MIN, T_IDLE_MAX)
			_play_animation("idle")
		CreatureState.WANDER:
			_pick_wander_target()
			_play_animation("walk")
		CreatureState.CURIOUS:
			_timer = T_CURIOUS
			_play_animation("curious")
		CreatureState.JUMP:
			_timer = 0.6
			_vel.y = -120.0
			apply_squash(-5.5)
			_spawn_particles(_local_pos + Vector2(0, 10), 5, 60.0, Color(0.75, 0.7, 0.6, 0.8))
			_play_animation("excited")
		CreatureState.LAND:
			_timer = T_LAND
			_vel.x *= 0.3
			apply_squash(7.0)
			_spawn_particles(_local_pos + Vector2(0, 10), 10, 80.0, Color(0.7, 0.65, 0.55, 0.9))
			_play_animation("alert")
		CreatureState.SLEEPY:
			_timer = T_SLEEPY
			_play_animation("sleep")
		CreatureState.STARTLED:
			_timer = T_STARTLE
			_vel = Vector2((randf() - 0.5) * 100.0, -80.0)
			apply_squash(-5.0)
			_spawn_particles(_local_pos, 12, 100.0, Color(0.9, 0.8, 1.0, 0.9))
			_play_animation("scared")

	state_changed.emit(_get_state_name())


func _get_state_name() -> String:
	match _state:
		CreatureState.IDLE: return "idle"
		CreatureState.WANDER: return "wander"
		CreatureState.CURIOUS: return "curious"
		CreatureState.JUMP: return "jump"
		CreatureState.LAND: return "land"
		CreatureState.SLEEPY: return "sleepy"
		CreatureState.STARTLED: return "startled"
	return "unknown"


# ═══════════════════════════════════════════════════════════════════════════════
# PROCESS
# ═══════════════════════════════════════════════════════════════════════════════

func _process(delta: float) -> void:
	if not _assembled or _sprite == null:
		return

	_timer -= delta

	# Blink timer: periodically play blink animation briefly
	_blink_timer -= delta
	if _blink_timer <= 0.0 and _state == CreatureState.IDLE:
		_blink_timer = randf_range(2.5, 5.0)
		# Brief blink: play blink anim then return to idle
		if _current_anim == "idle":
			_play_animation("blink")
			await get_tree().create_timer(0.5).timeout
			if _state == CreatureState.IDLE and _current_anim == "blink":
				_play_animation("idle")

	# State updates
	match _state:
		CreatureState.IDLE:
			_update_idle(delta)
		CreatureState.WANDER:
			_update_wander(delta)
		CreatureState.CURIOUS:
			_update_curious(delta)
		CreatureState.JUMP:
			_update_jump(delta)
		CreatureState.LAND:
			if _timer <= 0.0:
				_enter_state(CreatureState.IDLE)
		CreatureState.SLEEPY:
			if _timer <= 0.0:
				_enter_state(CreatureState.IDLE)
		CreatureState.STARTLED:
			_update_jump(delta)
			if _timer <= 0.0:
				_enter_state(CreatureState.IDLE)

	# Apply velocity
	_local_pos += _vel * delta
	_vel *= FRICTION

	# Keep in bounds
	_clamp_to_bounds()

	# Squash & stretch spring physics
	_update_spring(delta)

	# Trail afterimage capture
	_update_trail(delta)

	# Particle simulation
	_update_particles(delta)

	# Update sprite position + spring scale
	if _sprite != null:
		_sprite.position = _local_pos
		_sprite.flip_h = _facing < 0.0
		_sprite.scale = Vector2(_sprite_scale * _ss.x, _sprite_scale * _ss.y)
		# Sync crossfade sprite position
		if _crossfade_sprite != null and _crossfade_sprite.visible:
			_crossfade_sprite.position = _local_pos
			_crossfade_sprite.flip_h = _facing < 0.0
			_crossfade_sprite.scale = _sprite.scale

	# Redraw for particles + trail
	if _particles.size() > 0 or (_trail.size() > 0 and _vel.length() > TRAIL_VEL_THRESHOLD):
		queue_redraw()


func _update_idle(delta: float) -> void:
	# Mouse proximity triggers curiosity
	var mouse: Vector2 = get_local_mouse_position()
	if _local_pos.distance_to(mouse) < _target_size * 1.5:
		_enter_state(CreatureState.CURIOUS)
		return

	if _timer <= 0.0:
		var roll: float = randf()
		if roll < JUMP_CHANCE:
			_enter_state(CreatureState.JUMP)
		elif roll < JUMP_CHANCE + SLEEPY_CHANCE:
			_enter_state(CreatureState.SLEEPY)
		else:
			_enter_state(CreatureState.WANDER)


func _update_wander(delta: float) -> void:
	var diff: Vector2 = _wander_target - _local_pos
	var dist: float = diff.length()

	if dist < ARRIVE_DIST:
		_enter_state(CreatureState.IDLE)
		return

	var dir: Vector2 = diff.normalized()
	_vel += dir * MOVE_SPEED * delta
	_facing = sign(dir.x) if abs(dir.x) > 0.01 else _facing


func _update_curious(delta: float) -> void:
	# Look at mouse
	var mouse: Vector2 = get_local_mouse_position()
	_facing = sign(mouse.x - _local_pos.x) if abs(mouse.x - _local_pos.x) > 5.0 else _facing

	if _timer <= 0.0:
		_enter_state(CreatureState.IDLE)


func _update_jump(delta: float) -> void:
	# Simple gravity
	_vel.y += 400.0 * delta
	var bounds: Vector2 = _get_bounds()
	var ground_y: float = bounds.y * 0.65
	if _local_pos.y >= ground_y and _vel.y > 0.0:
		_local_pos.y = ground_y
		_vel.y = 0.0
		if _state == CreatureState.JUMP:
			_enter_state(CreatureState.LAND)


# ═══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

func _pick_wander_target() -> void:
	var bounds: Vector2 = _get_bounds()
	var margin: float = _target_size * 0.3
	_wander_target = Vector2(
		randf_range(margin, bounds.x - margin),
		randf_range(bounds.y * 0.5, bounds.y * 0.8)
	)


func _get_bounds() -> Vector2:
	var parent: Control = get_parent() as Control
	if parent != null:
		return parent.size
	return get_viewport_rect().size


func _clamp_to_bounds() -> void:
	var bounds: Vector2 = _get_bounds()
	var half: float = _target_size * 0.5
	_local_pos.x = clampf(_local_pos.x, half, bounds.x - half)
	_local_pos.y = clampf(_local_pos.y, half, bounds.y - half)


# ═══════════════════════════════════════════════════════════════════════════════
# SQUASH & STRETCH — Spring simulation
# ═══════════════════════════════════════════════════════════════════════════════

func _update_spring(delta: float) -> void:
	# Spring force toward rest (1.0, 1.0)
	var force_x: float = -SS_K * (_ss.x - SS_REST) - SS_DAMP * _ss_vel.x
	var force_y: float = -SS_K * (_ss.y - SS_REST) - SS_DAMP * _ss_vel.y
	_ss_vel.x += force_x * delta
	_ss_vel.y += force_y * delta
	_ss.x += _ss_vel.x * delta
	_ss.y += _ss_vel.y * delta
	# Volume preservation: sx = sqrt(1.0 / sy)
	_ss.x = sqrt(1.0 / maxf(_ss.y, 0.01))


func apply_squash(impulse_y: float) -> void:
	_ss_vel.y += impulse_y


# ═══════════════════════════════════════════════════════════════════════════════
# PARTICLES — CPU pixel dust via _draw()
# ═══════════════════════════════════════════════════════════════════════════════

func _spawn_particles(origin: Vector2, count: int, spread: float, color: Color) -> void:
	for i in range(count):
		if _particles.size() >= MAX_PARTICLES:
			break
		var angle: float = randf() * TAU
		var spd: float = randf_range(30.0, spread)
		var life: float = randf_range(0.35, 0.85)
		_particles.append({
			"pos": origin,
			"vel": Vector2(cos(angle) * spd, sin(angle) * spd - 60.0),
			"color": color,
			"life": life,
			"max_life": life,
		})


func _update_particles(delta: float) -> void:
	var i: int = _particles.size() - 1
	while i >= 0:
		var p: Dictionary = _particles[i]
		p["life"] -= delta
		if p["life"] <= 0.0:
			_particles.remove_at(i)
			i -= 1
			continue
		var vel: Vector2 = p["vel"]
		vel.y += PARTICLE_GRAVITY * delta
		vel.x *= PARTICLE_X_DAMP
		p["vel"] = vel
		p["pos"] = p["pos"] + vel * delta
		i -= 1


# ═══════════════════════════════════════════════════════════════════════════════
# TRAIL — Afterimage history
# ═══════════════════════════════════════════════════════════════════════════════

func _update_trail(delta: float) -> void:
	_trail_timer -= delta
	if _trail_timer > 0.0:
		return
	_trail_timer = TRAIL_INTERVAL

	# Only capture trail when moving fast enough
	if _vel.length() < TRAIL_VEL_THRESHOLD:
		_trail.clear()
		return

	_trail.append({
		"pos": _local_pos,
		"flip_h": _facing < 0.0,
		"scale": Vector2(_sprite_scale * _ss.x, _sprite_scale * _ss.y),
	})
	while _trail.size() > TRAIL_LENGTH:
		_trail.pop_front()


# ═══════════════════════════════════════════════════════════════════════════════
# SHADER SQUISH — UV push-deformation on click
# ═══════════════════════════════════════════════════════════════════════════════

func _apply_squish(local_click: Vector2) -> void:
	if _squish_material == null or _sprite == null:
		return
	# Convert click position to UV (0-1) relative to sprite
	var sprite_origin: Vector2 = _sprite.position - Vector2(64.0 * _sprite_scale, 64.0 * _sprite_scale)
	var sprite_size: float = 128.0 * _sprite_scale
	var uv: Vector2 = (local_click - sprite_origin) / sprite_size
	uv = uv.clamp(Vector2.ZERO, Vector2.ONE)

	_squish_material.set_shader_parameter("press_uv", uv)
	_squish_material.set_shader_parameter("press_strength", 1.0)

	# Tween strength back to 0
	var tween := create_tween()
	tween.tween_method(func(v: float):
		if _squish_material != null:
			_squish_material.set_shader_parameter("press_strength", v)
	, 1.0, 0.0, 0.3).set_ease(Tween.EASE_OUT).set_trans(Tween.TRANS_QUAD)


# ═══════════════════════════════════════════════════════════════════════════════
# DRAW — Particles + trail rendering
# ═══════════════════════════════════════════════════════════════════════════════

func _draw() -> void:
	# Draw trail afterimages (oldest = most transparent)
	if _trail.size() > 1 and _vel.length() > TRAIL_VEL_THRESHOLD and _sprite != null:
		var texture: Texture2D = _sprite.sprite_frames.get_frame_texture(_current_anim, _sprite.frame)
		if texture != null:
			for i in range(_trail.size() - 1):  # skip latest (current pos)
				var t: Dictionary = _trail[i]
				var alpha: float = lerpf(0.05, 0.20, float(i) / float(_trail.size()))
				var trail_scale: Vector2 = t["scale"]
				var trail_pos: Vector2 = t["pos"]
				# Draw with low alpha
				var offset: Vector2 = -Vector2(64.0, 64.0) * trail_scale
				var dest_rect := Rect2(trail_pos + offset, Vector2(128.0, 128.0) * trail_scale)
				var flip: bool = t["flip_h"]
				if flip:
					dest_rect.position.x += dest_rect.size.x
					dest_rect.size.x = -dest_rect.size.x
				draw_texture_rect(texture, dest_rect, false, Color(1, 1, 1, alpha))

	# Draw particles
	var px: float = maxf(2.0, _sprite_scale * 2.0)
	for p in _particles:
		var life_ratio: float = p["life"] / p["max_life"]
		var c: Color = p["color"]
		c.a = life_ratio
		draw_rect(Rect2(p["pos"] - Vector2(px * 0.5, px * 0.5), Vector2(px, px)), c)


# ═══════════════════════════════════════════════════════════════════════════════
# INPUT
# ═══════════════════════════════════════════════════════════════════════════════

func _gui_input(event: InputEvent) -> void:
	if event is InputEventMouseButton:
		var mb: InputEventMouseButton = event as InputEventMouseButton
		if mb.pressed and mb.button_index == MOUSE_BUTTON_LEFT:
			# Check if click is on the sprite
			var dist: float = _local_pos.distance_to(mb.position)
			if dist < _target_size * 0.6:
				creature_clicked.emit()
				# Squash & stretch on click
				apply_squash(4.0)
				# Shader squish deformation
				_apply_squish(mb.position)
				# Sparkle particles
				_spawn_particles(_local_pos, 6, 90.0, Color(1.0, 0.95, 0.7, 1.0))
				# React to click
				if _state != CreatureState.STARTLED:
					_enter_state(CreatureState.STARTLED)
				accept_event()


# ═══════════════════════════════════════════════════════════════════════════════
# GAMEPLAY API (same as BestioleCreature)
# ═══════════════════════════════════════════════════════════════════════════════

func react_to_event(event_type: String) -> void:
	"""React to game events with appropriate animation."""
	match event_type:
		"card_played":
			_enter_state(CreatureState.CURIOUS)
		"skill_used":
			_play_animation("alert")
			await get_tree().create_timer(1.0).timeout
			_play_animation("happy")
			await get_tree().create_timer(1.5).timeout
			_enter_state(CreatureState.IDLE)
		"danger":
			_play_animation("scared")
			await get_tree().create_timer(2.0).timeout
			_enter_state(CreatureState.IDLE)
		"victory":
			_enter_state(CreatureState.JUMP)
		"failure":
			_play_animation("sad")
			await get_tree().create_timer(2.5).timeout
			_enter_state(CreatureState.IDLE)
		_:
			pass


func set_bond_level(level: int) -> void:
	_bond_level = clampi(level, 0, 10)


func set_awen(value: int) -> void:
	_awen = clampi(value, 0, 7)


func look_at_position(target: Vector2) -> void:
	if _sprite == null:
		return
	var diff_x: float = target.x - _local_pos.x
	if abs(diff_x) > 5.0:
		_facing = sign(diff_x)
		_sprite.flip_h = _facing < 0.0
	# Subtle lean toward target (max 3 degrees)
	var lean: float = clampf(diff_x / 200.0, -0.05, 0.05)
	_sprite.rotation = lean


func set_aura_tint(color: Color) -> void:
	if _sprite != null:
		_sprite.modulate = color
	if _crossfade_sprite != null and _crossfade_sprite.visible:
		_crossfade_sprite.modulate = color


func pop_in() -> void:
	if _sprite == null:
		return
	_spawn_particles(_local_pos, 8, 100.0, Color(1.0, 1.0, 1.0, 0.9))
	apply_squash(-4.0)
	_sprite.scale = Vector2.ZERO
	var tween := create_tween()
	tween.tween_property(_sprite, "scale",
		Vector2(_sprite_scale, _sprite_scale), 0.4).set_ease(Tween.EASE_OUT).set_trans(Tween.TRANS_ELASTIC)
