"""LibreSprite Bridge — Generate sprites via LibreSprite CLI batch mode.

Pipeline: Python (grid + palette) → JS script → LibreSprite CLI → sprite sheet + .ase

Usage:
    from pixel_art.libresprite_bridge import forge_with_libresprite
    forge_with_libresprite("warrior", grids=[FRAME_0, FRAME_1], palette=PAL, fps=4)
"""

import os
import sys
import json
import subprocess
import tempfile

# Ensure pixel_art package is importable
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from pixel_art.merlin_pixel_forge import GridSprite

# LibreSprite executable path
LIBRESPRITE_EXE = os.environ.get(
    'LIBRESPRITE_PATH',
    'C:/Users/PGNK2128/LibreSprite/libresprite-v1.2/libresprite.exe'
)

# Godot project root
GODOT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
OUTPUT_DIR = os.path.join(GODOT_ROOT, 'output', 'pixel_art')


def _grid_to_rgba(grid, palette):
    """Convert a grid + palette to flat RGBA array.

    Args:
        grid: List of strings, each char = 1 pixel.
        palette: Dict of {char: (R, G, B, A)} or {char: (R, G, B)}.

    Returns:
        Tuple of (width, height, flat list of RGBA values).
    """
    max_width = max(len(row) for row in grid)
    padded = [row.ljust(max_width, '_') for row in grid]
    height = len(padded)
    width = max_width

    rgba = []
    for row in padded:
        for ch in row:
            color = palette.get(ch, (0, 0, 0, 0))
            if len(color) == 3:
                color = (*color, 255)
            rgba.extend(color)
    return width, height, rgba


def generate_sprite_script(name, grids, palette, fps=4):
    """Generate a LibreSprite JS script that creates a multi-frame sprite.

    The script expects to run on an already-open sprite (template).
    It will:
    1. Set pixels for frame 0 from the existing template
    2. Create additional frames and set their pixels
    3. Each frame gets RGBA data via putImageData()

    Args:
        name: Sprite name (for console output).
        grids: List of grid strings (one per frame).
        palette: Dict of {char: (R,G,B,A)}.
        fps: Animation FPS.

    Returns:
        JS script as string.
    """
    frames_data = []
    for grid in grids:
        w, h, rgba = _grid_to_rgba(grid, palette)
        frames_data.append({'w': w, 'h': h, 'rgba': rgba})

    # Build the JS script
    js_lines = [
        '// Auto-generated by Merlin Pixel Forge — LibreSprite Bridge',
        f'// Sprite: {name} | {len(grids)} frame(s) | {fps} FPS',
        '',
        'var sprite = app.activeSprite;',
        'if (!sprite) { console.log("ERROR: No active sprite"); }',
        'var layerNum = app.activeLayerNumber;',
        '',
    ]

    for i, fd in enumerate(frames_data):
        w, h = fd['w'], fd['h']

        # Encode RGBA as a JS array literal — chunked for large data
        rgba_str = json.dumps(fd['rgba'])

        js_lines.append(f'// === Frame {i} ({w}x{h}) ===')

        if i > 0:
            js_lines.append('app.command.setParameter("content", "current");')
            js_lines.append('app.command.NewFrame();')

        js_lines.append(f'var frame{i} = sprite.layer(layerNum).cel({i});')
        js_lines.append(f'var img{i} = frame{i}.image;')
        js_lines.append(f'var data{i} = new Uint8Array({rgba_str});')
        js_lines.append(f'img{i}.putImageData(data{i});')
        js_lines.append('')

    js_lines.append(f'console.log("[OK] {name}: {len(grids)} frames written");')
    return '\n'.join(js_lines)


def generate_effect_script(effect_type, params=None):
    """Generate a JS script for LibreSprite effects.

    Args:
        effect_type: 'outline', 'dither_floyd', 'dither_bayer', 'color_shift'.
        params: Dict of effect parameters.

    Returns:
        JS script as string.
    """
    if params is None:
        params = {}

    if effect_type == 'outline':
        color = params.get('color', [20, 18, 15, 255])
        return f"""// Auto-generated — Outline effect
var sprite = app.activeSprite;
var layerNum = app.activeLayerNumber;
var frameCount = sprite.totalFrames || 1;
var col = app.pixelColor;
var outlineColor = col.rgba({color[0]}, {color[1]}, {color[2]}, {color[3]});

for (var f = 0; f < frameCount; f++) {{
    var cel = sprite.layer(layerNum).cel(f);
    if (!cel) continue;
    var img = cel.image;
    var w = img.width;
    var h = img.height;
    var src = img.getImageData();
    var dst = new Uint8Array(src.length);

    // Copy source
    for (var i = 0; i < src.length; i++) dst[i] = src[i];

    // Add outline: for each transparent pixel adjacent to opaque pixel
    for (var y = 0; y < h; y++) {{
        for (var x = 0; x < w; x++) {{
            var idx = (y * w + x) * 4;
            if (src[idx + 3] > 0) continue;  // Skip opaque pixels

            var hasNeighbor = false;
            var dirs = [[-1,0],[1,0],[0,-1],[0,1],[-1,-1],[1,-1],[-1,1],[1,1]];
            for (var d = 0; d < dirs.length; d++) {{
                var nx = x + dirs[d][0];
                var ny = y + dirs[d][1];
                if (nx >= 0 && nx < w && ny >= 0 && ny < h) {{
                    var ni = (ny * w + nx) * 4;
                    if (src[ni + 3] > 0) {{ hasNeighbor = true; break; }}
                }}
            }}
            if (hasNeighbor) {{
                dst[idx] = {color[0]};
                dst[idx+1] = {color[1]};
                dst[idx+2] = {color[2]};
                dst[idx+3] = {color[3]};
            }}
        }}
    }}

    img.putImageData(dst);
}}
console.log("[OK] Outline applied to " + frameCount + " frames");
"""

    if effect_type == 'breathing':
        amplitude = params.get('amplitude', 1)
        return f"""// Auto-generated — Breathing animation (shift sprite up/down)
var sprite = app.activeSprite;
var layerNum = app.activeLayerNumber;
var cel0 = sprite.layer(layerNum).cel(0);
var img0 = cel0.image;
var w = img0.width;
var h = img0.height;
var src = img0.getImageData();
var amp = {amplitude};

// Frame pattern: neutral, up, neutral, down
var offsets = [0, -amp, 0, amp];

for (var f = 1; f < offsets.length; f++) {{
    app.command.setParameter("content", "current");
    app.command.NewFrame();
    var cel = sprite.layer(layerNum).cel(f);
    var img = cel.image;
    var dst = new Uint8Array(w * h * 4);  // All transparent

    var dy = offsets[f];
    for (var y = 0; y < h; y++) {{
        var srcY = y - dy;
        if (srcY < 0 || srcY >= h) continue;
        for (var x = 0; x < w; x++) {{
            var si = (srcY * w + x) * 4;
            var di = (y * w + x) * 4;
            dst[di] = src[si];
            dst[di+1] = src[si+1];
            dst[di+2] = src[si+2];
            dst[di+3] = src[si+3];
        }}
    }}
    img.putImageData(dst);
}}
console.log("[OK] Breathing animation: 4 frames, amplitude=" + amp);
"""

    raise ValueError(f"Unknown effect: {effect_type}")


def _create_template_png(width, height, output_path):
    """Create a blank transparent PNG template using Pillow.

    Args:
        width: Image width.
        height: Image height.
        output_path: Path to save the PNG.
    """
    from PIL import Image
    img = Image.new('RGBA', (width, height), (0, 0, 0, 0))
    img.save(output_path, 'PNG')


def run_libresprite_batch(input_path, script_path=None, save_as=None,
                          sheet=None, sheet_data=None, sheet_type='horizontal',
                          scale=None, verbose=False):
    """Run LibreSprite in batch mode.

    Args:
        input_path: Input sprite file (.png, .ase, .aseprite).
        script_path: Optional JS script to execute.
        save_as: Optional output path (.ase, .png, .gif).
        sheet: Optional sprite sheet output path (.png).
        sheet_data: Optional JSON metadata output path.
        sheet_type: Sheet layout ('horizontal', 'vertical', 'rows', 'columns', 'packed').
        scale: Optional scale factor.
        verbose: Print command output.

    Returns:
        Dict with 'success', 'stdout', 'stderr', 'returncode'.
    """
    if not os.path.isfile(LIBRESPRITE_EXE):
        return {
            'success': False,
            'error': f'LibreSprite not found at: {LIBRESPRITE_EXE}'
        }

    cmd = [LIBRESPRITE_EXE, '-b']

    if verbose:
        cmd.append('--verbose')

    cmd.append(input_path)

    if script_path:
        cmd.extend(['--script', script_path])

    if scale:
        cmd.extend(['--scale', str(scale)])

    if sheet:
        cmd.extend(['--sheet', sheet])
        cmd.extend(['--sheet-type', sheet_type])

    if sheet_data:
        cmd.extend(['--data', sheet_data])
        cmd.extend(['--format', 'json-hash'])
        cmd.append('--list-layers')
        cmd.append('--list-tags')

    if save_as:
        cmd.extend(['--save-as', save_as])

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60,
            encoding='utf-8',
            errors='replace'
        )

        if verbose:
            if result.stdout:
                print(f"  [STDOUT] {result.stdout.strip()}")
            if result.stderr:
                print(f"  [STDERR] {result.stderr.strip()}")

        return {
            'success': result.returncode == 0,
            'stdout': result.stdout,
            'stderr': result.stderr,
            'returncode': result.returncode,
            'cmd': ' '.join(cmd)
        }
    except subprocess.TimeoutExpired:
        return {'success': False, 'error': 'LibreSprite timed out (60s)'}
    except FileNotFoundError:
        return {'success': False, 'error': f'LibreSprite not found: {LIBRESPRITE_EXE}'}


def forge_with_libresprite(name, grids, palette, fps=4, scale_preview=8,
                           effects=None, godot_integrate=True,
                           open_preview=True, verbose=True):
    """Full pipeline: grids -> LibreSprite -> sprite sheet + .ase + Godot.

    Args:
        name: Sprite name.
        grids: List of grid strings (one per frame).
        palette: Dict of {char: (R,G,B,A)}.
        fps: Animation FPS.
        scale_preview: Upscale factor for preview.
        effects: List of effect dicts, e.g. [{'type': 'outline', 'color': [0,0,0,255]}].
        godot_integrate: If True, integrate into Godot project.
        open_preview: If True, generate HTML preview.
        verbose: Print progress.

    Returns:
        Dict with all generated file paths.
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    result = {'name': name, 'files': []}

    # Validate grid dimensions
    w, h, _ = _grid_to_rgba(grids[0], palette)
    frame_count = len(grids)

    if verbose:
        print(f"\n{'='*55}")
        print(f"  MERLIN PIXEL FORGE x LibreSprite -- {name}")
        print(f"  {w}x{h} | {frame_count} frame(s) | {fps} FPS")
        print(f"{'='*55}\n")

    from pixel_art.merlin_pixel_forge import upscale
    from pixel_art.effects import outline as pillow_outline
    from pixel_art.animation import SpriteSheet, export_gif
    from pixel_art.ase_writer import write_ase

    # Render all frames with Pillow
    sprites = [GridSprite(g, palette, name) for g in grids]
    frames = [s.render() for s in sprites]

    # 1. Native .ase file (direct binary write — no LibreSprite needed)
    ase_path = os.path.join(OUTPUT_DIR, f'{name}.ase')
    write_ase(ase_path, frames, fps=fps, layer_name=name)
    result['files'].append(ase_path)
    result['ase'] = ase_path
    if verbose:
        print(f"  [1/7] ASE file: {ase_path}")

    # 2. Native PNG (frame 0)
    native_path = os.path.join(OUTPUT_DIR, f'{name}.png')
    sprites[0].export_png(native_path)
    result['files'].append(native_path)
    if verbose:
        print(f"  [2/7] PNG: {native_path}")

    # 3. Upscaled preview
    preview_path = os.path.join(OUTPUT_DIR, f'{name}_{w*scale_preview}x{h*scale_preview}.png')
    sprites[0].export_preview(preview_path, scale=scale_preview, background=(40, 40, 45))
    result['files'].append(preview_path)
    if verbose:
        print(f"  [3/7] Preview {scale_preview}x: {preview_path}")

    # 4. Outlined preview
    outlined = pillow_outline(frames[0], color=(20, 18, 15, 255))
    outlined_up = upscale(outlined, scale_preview)
    outlined_path = os.path.join(OUTPUT_DIR, f'{name}_outlined.png')
    outlined_up.save(outlined_path, 'PNG')
    result['files'].append(outlined_path)
    if verbose:
        print(f"  [4/7] Outlined: {outlined_path}")

    # 5. Sprite sheet + GIF (if animated)
    if frame_count > 1:
        sheet_path = os.path.join(OUTPUT_DIR, f'{name}_sheet.png')
        sheet_obj = SpriteSheet(frames, columns=frame_count)
        sheet_obj.export(sheet_path)
        result['files'].append(sheet_path)
        result['sheet'] = sheet_path

        gif_path = os.path.join(OUTPUT_DIR, f'{name}.gif')
        export_gif(frames, gif_path, fps=fps, scale=scale_preview)
        result['files'].append(gif_path)
        result['gif'] = gif_path

        if verbose:
            print(f"  [5/7] Sheet + GIF: {sheet_path}")

        # 5b. LibreSprite re-export from .ase (if available)
        if os.path.isfile(LIBRESPRITE_EXE):
            ls_sheet = os.path.join(OUTPUT_DIR, f'{name}_ls_sheet.png')
            ls_data = os.path.join(OUTPUT_DIR, f'{name}_ls_sheet.json')
            batch_result = run_libresprite_batch(
                input_path=ase_path,
                sheet=ls_sheet,
                sheet_data=ls_data,
                sheet_type='horizontal',
            )
            if os.path.isfile(ls_sheet):
                result['files'].append(ls_sheet)
                result['ls_sheet'] = ls_sheet
                if verbose:
                    print(f"        LibreSprite sheet: {ls_sheet}")
            if os.path.isfile(ls_data):
                result['files'].append(ls_data)
    elif verbose:
        print(f"  [5/7] Static sprite (no animation)")

    # 6. Apply effects via LibreSprite (if any and LibreSprite available)
    if effects and os.path.isfile(LIBRESPRITE_EXE):
        with tempfile.TemporaryDirectory(prefix='merlin_eff_') as tmpdir:
            for eff in effects:
                eff_type = eff.get('type', '')
                eff_params = {k: v for k, v in eff.items() if k != 'type'}
                try:
                    eff_script = generate_effect_script(eff_type, eff_params)
                    eff_path = os.path.join(tmpdir, f'{name}_eff_{eff_type}.js')
                    with open(eff_path, 'w', encoding='utf-8') as f:
                        f.write(eff_script)

                    eff_output = os.path.join(OUTPUT_DIR, f'{name}_{eff_type}.ase')
                    run_libresprite_batch(
                        input_path=ase_path,
                        script_path=eff_path,
                        save_as=eff_output,
                    )
                    if os.path.isfile(eff_output):
                        result['files'].append(eff_output)
                        if verbose:
                            print(f"  [6/7] Effect '{eff_type}': {eff_output}")
                except ValueError as e:
                    if verbose:
                        print(f"  [6/7] Effect '{eff_type}': skipped ({e})")
    elif verbose:
        print(f"  [6/7] Effects: " + ("none requested" if not effects else "LibreSprite not found"))

    # 7. HTML Preview + Godot integration
    if open_preview:
        from pixel_art.previewer import generate_preview
        preview_html = generate_preview(frames, palette, name, OUTPUT_DIR, w, h, fps)
        result['preview'] = preview_html
        result['files'].append(preview_html)
        if verbose:
            print(f"  [7/7] HTML preview: {preview_html}")

    if godot_integrate:
        from pixel_art.godot_integration import integrate_sprite
        godot_result = integrate_sprite(
            frames, name, GODOT_ROOT,
            sprites_dir="sprites/pixel_art",
            fps=fps,
        )
        result['godot'] = godot_result
        if verbose:
            for key, val in godot_result.items():
                print(f"  [GODOT:{key.upper()}] {val}")

    # Summary
    unique_files = list(set(result['files']))
    result['files'] = unique_files
    if verbose:
        print(f"\n  Total: {len(unique_files)} output files")
        if 'ase' in result:
            print(f"\n  > LibreSprite editable: {result['ase']}")
            print(f"    Open with: libresprite.exe \"{result['ase']}\"")
        if 'preview' in result:
            print(f"  > VS Code preview: {result['preview']}")

    return result


if __name__ == "__main__":
    # Demo: generate a celtic warrior with LibreSprite
    from pixel_art.examples.celtic_warrior import FRAME_0, FRAME_1, FRAME_2, PALETTE
    forge_with_libresprite(
        name="celtic_warrior_ls",
        grids=[FRAME_0, FRAME_1, FRAME_0, FRAME_2],
        palette=PALETTE,
        fps=4,
        effects=[{'type': 'outline', 'color': [20, 18, 15, 255]}],
    )
